"""Deterministic Sandbox Verifier for Platform Generation."""

import os
import sys
import re
import json
import tempfile
import subprocess
from dataclasses import dataclass
from typing import Dict, Any, Tuple, Optional
from .sandbox_env import AgentWorkspace

@dataclass
class VerificationScore:
    build_passed: bool
    test_passed: bool
    smoke_passed: bool
    telemetry_passed: bool
    pass_rate: float
    total_tests: int
    score_penalty: float
    details: str

class DeterministicSandboxVerifier:
    """Evaluates candidate platform packages generated by virtual enterprises, supporting live workspace execution."""

    def __init__(self, work_dir: str = "/tmp/sandbox_verification"):
        self.work_dir = work_dir
        os.makedirs(self.work_dir, exist_ok=True)

    def extract_code_blocks(self, text: str) -> Dict[str, str]:
        """Extracts files and code blocks embedded in a firm's final deliverable text."""
        files: Dict[str, str] = {}
        pattern = r'(?:###\s*File:\s*[`"]?([a-zA-Z0-9_\-\.\/]+)[`"]?|```(?:python|yaml|toml)\s*#?\s*([a-zA-Z0-9_\-\.\/]+)?)\n(.*?)```'
        matches = re.findall(pattern, text, re.DOTALL)
        for m in matches:
            filename = m[0] or m[1]
            content = m[2]
            if filename and ("." in filename):
                files[filename.strip()] = content.strip()
        return files

    def verify_package(
        self,
        company_id: str,
        deliverable_text: str,
        workspace: Optional[AgentWorkspace] = None
    ) -> VerificationScore:
        """Executes a 4-gate deterministic verification on the firm's code (workspace on disk or extracted text)."""
        if workspace and workspace.list_files():
            extracted_files = workspace.export_bundle()
            is_live_workspace = True
        else:
            extracted_files = self.extract_code_blocks(deliverable_text)
            is_live_workspace = False

        # Gate 1: Check if essential package components exist
        has_pyproject = any("pyproject.toml" in f or "setup.py" in f for f in extracted_files.keys())
        has_runtime = any("runtime" in f or "company" in f or "engine" in f or "orchestrator" in f or "core" in f for f in extracted_files.keys())
        build_passed = has_pyproject and has_runtime

        # Gate 2: Smoke test (>= 3 distinct files + core module)
        smoke_passed = has_runtime and len(extracted_files) >= 3

        # Gate 3: Telemetry hooks verified
        all_code = " ".join(extracted_files.values()) + " " + deliverable_text
        has_telemetry = any("telemetry" in f or "trace" in f or "otel" in f for f in extracted_files.keys()) or ("opentelemetry" in all_code.lower() or "tracer.start_as_current_span" in all_code.lower())
        telemetry_passed = bool(has_telemetry)

        # Gate 4: Test gate (run live pytest/unittest if workspace exists, otherwise check test files exist)
        has_test_files = any("test" in f for f in extracted_files.keys())
        if is_live_workspace and has_test_files:
            test_res = workspace.execute_bash("python3 -m pytest tests/ -q", timeout=15)
            if test_res.get("exit_code") == 0:
                test_passed = True
            elif "No module named pytest" in test_res.get("stderr", ""):
                unit_res = workspace.execute_bash("python3 -m unittest discover -s tests/ -p 'test_*.py'", timeout=15)
                test_passed = (unit_res.get("exit_code") == 0) or any("def test_" in c or "assert " in c for f, c in extracted_files.items() if "test" in f)
            else:
                test_passed = False
        else:
            test_passed = has_test_files

        # Calculate empirical pass rate
        checks = [build_passed, smoke_passed, telemetry_passed, test_passed]
        passed_count = sum(1 for c in checks if c)
        pass_rate = passed_count / len(checks)

        source_label = "Live Sandbox" if is_live_workspace else "Extracted"
        details = (
            f"[{source_label}] {len(extracted_files)} files. "
            f"Build: {'PASS' if build_passed else 'FAIL'}, "
            f"Smoke: {'PASS' if smoke_passed else 'FAIL'}, "
            f"Telemetry: {'PASS' if telemetry_passed else 'FAIL'}, "
            f"Tests: {'PASS' if test_passed else 'FAIL'}."
        )

        return VerificationScore(
            build_passed=build_passed,
            test_passed=test_passed,
            smoke_passed=smoke_passed,
            telemetry_passed=telemetry_passed,
            pass_rate=pass_rate,
            total_tests=len(checks),
            score_penalty=round((1.0 - pass_rate) * 25.0, 2),
            details=details
        )
