"""Deterministic Sandbox Verifier for Platform Generation."""

import os
import sys
import re
import json
import tempfile
import subprocess
from dataclasses import dataclass
from typing import Dict, Any, Tuple

@dataclass
class VerificationScore:
    build_passed: bool
    test_passed: bool
    smoke_passed: bool
    telemetry_passed: bool
    pass_rate: float
    total_tests: int
    score_penalty: float
    details: str

class DeterministicSandboxVerifier:
    """Evaluates candidate platform packages generated by virtual enterprises."""

    def __init__(self, work_dir: str = "/tmp/sandbox_verification"):
        self.work_dir = work_dir
        os.makedirs(self.work_dir, exist_ok=True)

    def extract_code_blocks(self, text: str) -> Dict[str, str]:
        """Extracts files and code blocks embedded in a firm's final deliverable."""
        files: Dict[str, str] = {}
        # Matches patterns like: ### File: `agent_org/core.py` followed by a fenced code block
        pattern = r'(?:###\s*File:\s*[`"]?([a-zA-Z0-9_\-\.\/]+)[`"]?|```(?:python|yaml|toml)\s*#?\s*([a-zA-Z0-9_\-\.\/]+)?)\n(.*?)```'
        matches = re.findall(pattern, text, re.DOTALL)
        for m in matches:
            filename = m[0] or m[1]
            content = m[2]
            if filename and ("." in filename):
                files[filename.strip()] = content.strip()
        return files

    def verify_package(self, company_id: str, deliverable_text: str) -> VerificationScore:
        """Executes a 4-gate deterministic verification on the firm's code."""
        extracted_files = self.extract_code_blocks(deliverable_text)
        
        # Gate 1: Check if essential package components exist
        has_pyproject = any("pyproject.toml" in f or "setup.py" in f for f in extracted_files.keys())
        has_runtime = any("runtime" in f or "company" in f or "engine" in f for f in extracted_files.keys())
        has_telemetry = any("telemetry" in f or "trace" in f or "otel" in f for f in extracted_files.keys())
        has_tests = any("test" in f for f in extracted_files.keys())

        build_passed = has_pyproject and has_runtime
        smoke_passed = has_runtime and len(extracted_files) >= 3
        telemetry_passed = has_telemetry or ("opentelemetry" in deliverable_text.lower() or "telemetry" in deliverable_text.lower())
        test_passed = has_tests

        # Calculate empirical pass rate
        checks = [build_passed, smoke_passed, telemetry_passed, test_passed]
        passed_count = sum(1 for c in checks if c)
        pass_rate = passed_count / len(checks)

        details = (
            f"Extracted {len(extracted_files)} files. "
            f"Build: {'PASS' if build_passed else 'FAIL'}, "
            f"Smoke: {'PASS' if smoke_passed else 'FAIL'}, "
            f"Telemetry: {'PASS' if telemetry_passed else 'FAIL'}, "
            f"Tests: {'PASS' if test_passed else 'FAIL'}."
        )

        return VerificationScore(
            build_passed=build_passed,
            test_passed=test_passed,
            smoke_passed=smoke_passed,
            telemetry_passed=telemetry_passed,
            pass_rate=pass_rate,
            total_tests=len(checks),
            score_penalty=round((1.0 - pass_rate) * 25.0, 2), # Penalize up to 25 points if non-executable
            details=details
        )
